Trin 1: Indlæsning af Data
Først vil jeg indlæse de forskellige CSV-filer, du har uploadet, i pandas dataframes.
Når jeg kører dette script, vil det indlæse hver CSV-fil og vise de første par rækker af hver dataframe med en passende overskrift for at identificere dem. Dette hjælper mig med at få et hurtigt overblik over strukturen af hver enkelt datasæt.

In [15]:
import pandas as pd

# Liste over filnavne og deres labels
files = [
    ('MPS Borough Level Crime (Historical).csv', 'Historical Crime Data'),
    ('MPS Borough Level Crime (most recent 24 months).csv', 'Recent Crime Data'),
    ('MPS LSOA Level Crime (Historical).csv', 'Historical LSOA Crime Data'),
    ('MPS LSOA Level Crime (most recent 24 months).csv', 'Recent LSOA Crime Data'),
    ('MPS Ward Level Crime (Historical).csv', 'Historical Ward Crime Data'),
    ('MPS Ward Level Crime (most recent 24 months).csv', 'Recent Ward Crime Data'),
    ('reported.csv', 'Reported Crime Data'),
    ('SYB63_328_202009_Intentional Homicides and Other Crimes.csv', 'Homicides Crime Data')
]

# Indlæsning af CSV-filer og visning af de første par rækker
for file, label in files:
    df = pd.read_csv(file)
    print(f"--- {label} ---")
    print(df.head(), '\n')

--- Historical Crime Data ---
                   MajorText                        MinorText  \
0  ARSON AND CRIMINAL DAMAGE                            ARSON
1  ARSON AND CRIMINAL DAMAGE                  CRIMINAL DAMAGE
2                   BURGLARY  BURGLARY BUSINESS AND COMMUNITY
3                   BURGLARY           BURGLARY IN A DWELLING
4              DRUG OFFENCES              POSSESSION OF DRUGS

            BoroughName  201004  201005  201006  201007  201008  201009  \
0  Barking and Dagenham       6       5      11      10       6       6
1  Barking and Dagenham     204     190     218     217     203     161
2  Barking and Dagenham      48      58      58      46      46      51
3  Barking and Dagenham     116     102     124     137     153     136
4  Barking and Dagenham      76      64      82      72      98      87

   201010  ...  202107  202108  202109  202110  202111  202112  202201  \
0      13  ...       3      12       5       7       5       1       3
1     196  ...     126     140     112     120     105     114     123
2      53  ...      21      28      25      37      20      14      18
3     116  ...      59      85      56      82      82      92      78
4     109  ...     129     101     115     108     112      87     113

   202202  202203  202204
0       3       2       5
1     107     111     124
2      28      27      15
3      65      73      79
4     123     127      70

[5 rows x 148 columns]

--- Recent Crime Data ---
                   MajorText                        MinorText  \
0  ARSON AND CRIMINAL DAMAGE                            ARSON
1  ARSON AND CRIMINAL DAMAGE                  CRIMINAL DAMAGE
2                   BURGLARY           BURGLARY - RESIDENTIAL
3                   BURGLARY  BURGLARY BUSINESS AND COMMUNITY
4                   BURGLARY           BURGLARY IN A DWELLING

            BoroughName  202205  202206  202207  202208  202209  202210  \
0  Barking and Dagenham       6       5       9       5       4       4
1  Barking and Dagenham     111     136     112     127     100     138
2  Barking and Dagenham       0       0       0       0       0       0
3  Barking and Dagenham      15      23      18      27      29      25
4  Barking and Dagenham      70      51      44      72      75      78

   202211  ...  202307  202308  202309  202310  202311  202312  202401  \
0       3  ...       5       7       4       4       3       4       4
1     101  ...     131     114     129      82      89     125     127
2       0  ...       0       0       0       0       0       0       0
3      21  ...      25      34      40      26      19      20      31
4      64  ...      48      75      86      63      64      53      67

   202402  202403  202404
0       5       6       3
1     126     131     109
2       2      50      51
3      21      30      24
4      47       0       0

[5 rows x 27 columns]

--- Historical LSOA Crime Data ---
   LSOA Code                  LSOA Name    Borough             Major Category  \
0  E01000006  Barking and Dagenham 016A  E09000002  Arson and Criminal Damage
1  E01000006  Barking and Dagenham 016A  E09000002  Arson and Criminal Damage
2  E01000006  Barking and Dagenham 016A  E09000002                   Burglary
3  E01000006  Barking and Dagenham 016A  E09000002                   Burglary
4  E01000006  Barking and Dagenham 016A  E09000002              Drug Offences

                    Minor Category  201903  201904  201905  201906  201907  \
0                            Arson       1       0       0       0       0
1                  Criminal Damage       1       2       0       1       0
2  Burglary Business and Community       0       0       0       0       0
3                Domestic Burglary       1       0       3       1       0
4                 Drug Trafficking       0       0       0       0       0

   ...  202102  202103  202104  202105  202106  202107  202108  202109  \
0  ...       0       0       0       0       0       0       0       0
1  ...       1       0       0       1       1       0       0       0
2  ...       0       0       0       0       1       0       0       0
3  ...       0       0       0       0       0       0       0       0
4  ...       1       0       0       0       0       0       0       0

   202110  202111
0       0       0
1       0       0
2       0       0
3       1       1
4       0       0

[5 rows x 145 columns]

--- Recent LSOA Crime Data ---
   LSOA Code                  LSOA Name    Borough  \
0  E01000006  Barking and Dagenham 016A  E09000002
1  E01000006  Barking and Dagenham 016A  E09000002
2  E01000006  Barking and Dagenham 016A  E09000002
3  E01000006  Barking and Dagenham 016A  E09000002
4  E01000006  Barking and Dagenham 016A  E09000002

                         Major Category       Minor Category  202112  202201  \
0             Arson and Criminal Damage      Criminal Damage       1       2
1                              Burglary    Domestic Burglary       1       0
2                         Drug Offences     Drug Trafficking       0       0
3                         Drug Offences  Possession of Drugs       2       5
4  Miscellaneous Crimes Against Society    Dangerous Driving       0       0

   202202  202203  202204  ...  202302  202303  202304  202305  202306  \
0       1       0       0  ...       0       1       1       0       0
1       0       1       0  ...       0       0       1       0       0
2       0       0       0  ...       0       0       1       0       1
3       2       1       1  ...       0       0       0       0       1
4       1       0       0  ...       0       0       0       0       0

   202307  202308  202309  202310  202311
0       2       0       0       1       0
1       0       1       0       0       1
2       0       0       0       0       0
3       0       2       0       0       0
4       0       0       0       0       0

[5 rows x 29 columns]

--- Historical Ward Crime Data ---
            WardName   WardCode                             MajorText  \
0  Heathrow Villages  E05013570             Arson and Criminal Damage
1  Heathrow Villages  E05013570  Miscellaneous Crimes Against Society
2  Heathrow Villages  E05013570                                 Theft
3  Heathrow Villages  E05013570                                 Theft
4  Heathrow Villages  E05013570                      Vehicle Offences

                    MinorText        LookUp_BoroughName  201004  201005  \
0             Criminal Damage  Aviation Security (SO18)       0       0
1   Other Notifiable Offences  Aviation Security (SO18)       0       0
2                 Other Theft  Aviation Security (SO18)       0       0
3                 Shoplifting  Aviation Security (SO18)       0       0
4  Theft from a Motor Vehicle  Aviation Security (SO18)       0       0

   201006  201007  201008  ...  202104  202105  202106  202107  202108  \
0       0       0       0  ...       0       0       0       0       0
1       0       0       0  ...       0       0       0       0       0
2       0       0       0  ...       0       0       0       0       0
3       0       0       0  ...       0       0       0       0       0
4       0       0       0  ...       0       0       0       0       0

   202109  202110  202111  202112  202201
0       0       0       0       0       0
1       0       0       0       0       0
2       0       0       0       0       0
3       0       0       0       0       0
4       0       0       0       0       0

[5 rows x 147 columns]

--- Recent Ward Crime Data ---
                   MajorText                        MinorText  \
0  Arson and Criminal Damage                            Arson
1  Arson and Criminal Damage                  Criminal Damage
2                   Burglary  Burglary Business and Community
3                   Burglary                Domestic Burglary
4              Drug Offences                 Drug Trafficking

            WardName   WardCode        LookUp_BoroughName  202202  202203  \
0  Heathrow Villages  E05013570  Aviation Security (SO18)       0       0
1  Heathrow Villages  E05013570  Aviation Security (SO18)       0       0
2  Heathrow Villages  E05013570  Aviation Security (SO18)       0       0
3  Heathrow Villages  E05013570  Aviation Security (SO18)       0       0
4  Heathrow Villages  E05013570  Aviation Security (SO18)       0       0

   202204  202205  202206  ...  202304  202305  202306  202307  202308  \
0       0       0       0  ...       0       2       2       2       0
1       0       0       0  ...       0      13      18      16      23
2       0       0       0  ...       1       4       2       2       4
3       0       0       0  ...       0       7       5       8      14
4       0       0       0  ...       0       5       3       2       5

   202309  202310  202311  202312  202401
0       0       0       0       1       3
1      24      19      17      36      26
2       6       3       1       4       2
3      14       1      10      11      12
4       3       3       0       4       3

[5 rows x 29 columns]

--- Reported Crime Data ---
   Year  crimes.total  crimes.penal.code  crimes.person  murder  assault  \
0  1950          2784               2306            120       1      105
1  1951          3284               2754            125       1      109
2  1952          3160               2608            119       1      104
3  1953          2909               2689            119       1      105
4  1954          3028               2791            126       1      107

   sexual.offenses  rape  stealing.general  burglary  ...  vehicle.theft  \
0               40     5              1578       295  ...            NaN
1               45     6              1899       342  ...            NaN
2               39     4              1846       372  ...            NaN
3               45     5              1929       361  ...            NaN
4               41     5              1981       393  ...            NaN

   out.of.vehicle.theft  shop.theft  robbery  fraud  criminal.damage  \
0                   NaN         NaN        3    209               72
1                   NaN         NaN        3    310               73
2                   NaN         NaN        3    217               82
3                   NaN         NaN        4    209               88
4                   NaN         NaN        4    236              101

   other.penal.crimes  narcotics  drunk.driving  population
0                 477        0.0             49     7014000
1                 530        0.0             66     7073000
2                 553        0.0             78     7125000
3                 220        0.0             91     7171000
4                 237        0.0            103     7213000

[5 rows x 21 columns]

--- Homicides Crime Data ---
                   T11 Intentional homicides and other crimes Unnamed: 2  \
0  Region/Country/Area                                    NaN       Year
1                    1          Total, all countries or areas       2005
2                    1          Total, all countries or areas       2005
3                    1          Total, all countries or areas       2005
4                    1          Total, all countries or areas       2010

                                          Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0                                             Series      Value  Footnotes
1             Intentional homicide rates per 100,000     6.2935        NaN
2  Percentage of male and female intentional homi...    10.0798        NaN
3  Percentage of male and female intentional homi...     2.4473        NaN
4             Intentional homicide rates per 100,000     6.0228        NaN

                                          Unnamed: 6
0                                             Source
1  United Nations Office on Drugs and Crime (UNOD...
2  United Nations Office on Drugs and Crime (UNOD...
3  United Nations Office on Drugs and Crime (UNOD...
4  United Nations Office on Drugs and Crime (UNOD...

Trin 2: Forstå Dataene
Nu hvor dataene er indlæst, kan jeg udforske dem for at forstå deres struktur, manglende værdier og eventuelle nødvendige transformationsprocesser.

In [3]:
# overblik over datasæts struktur og manglende værdier
print("Historical Crime Data Info:")
print(historical_crime_data.info())
print("\nRecent Crime Data Info:")
print(recent_crime_data.info())
print("\nHistorical LSOA Crime Data Info:")
print(historical_lsoa_crime_data.info())
print("\nRecent LSOA Crime Data Info:")
print(recent_lsoa_crime_data.info())
print("\nHistorical Ward Crime Data Info:")
print(historical_ward_crime_data.info())
print("\nRecent Ward Crime Data Info:")
print(recent_ward_crime_data.info())
print("\nReported Crime Data Info:")
print(reported_crime_data.info())
print("\nHomicides Crime Data Info:")
print(homicides_crime_data.info())

# Descriptive statistics for at forstå datafordelingen
print("\nHistorical Crime Data Description:")
print(historical_crime_data.describe())
print("\nRecent Crime Data Description:")
print(recent_crime_data.describe())
print("\nHistorical LSOA Crime Data Description:")
print(historical_lsoa_crime_data.describe())
print("\nRecent LSOA Crime Data Description:")
print(recent_lsoa_crime_data.describe())
print("\nHistorical Ward Crime Data Description:")
print(historical_ward_crime_data.describe())
print("\nRecent Ward Crime Data Description:")
print(recent_ward_crime_data.describe())
print("\nReported Crime Data Description:")
print(reported_crime_data.describe())
print("\nHomicides Crime Data Description:")
print(homicides_crime_data.describe())

Historical Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Columns: 148 entries, MajorText to 202204
dtypes: int64(145), object(3)
memory usage: 1.1+ MB
None

Recent Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MajorText    999 non-null    object
 1   MinorText    999 non-null    object
 2   BoroughName  999 non-null    object
 3   202205       999 non-null    int64
 4   202206       999 non-null    int64
 5   202207       999 non-null    int64
 6   202208       999 non-null    int64
 7   202209       999 non-null    int64
 8   202210       999 non-null    int64
 9   202211       999 non-null    int64
 10  202212       999 non-null    int64
 11  202301       999 non-null    int64
 12  202302       999 non-null    int64
 13  202303       999 non-null    int64
 14  202304       999 non-null    int64
 15  202305       999 non-null    int64
 16  202306       999 non-null    int64
 17  202307       999 non-null    int64
 18  202308       999 non-null    int64
 19  202309       999 non-null    int64
 20  202310       999 non-null    int64
 21  202311       999 non-null    int64
 22  202312       999 non-null    int64
 23  202401       999 non-null    int64
 24  202402       999 non-null    int64
 25  202403       999 non-null    int64
 26  202404       999 non-null    int64
dtypes: int64(24), object(3)
memory usage: 210.9+ KB
None

Historical LSOA Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153453 entries, 0 to 153452
Columns: 145 entries, LSOA Code to 202111
dtypes: int64(140), object(5)
memory usage: 169.8+ MB
None

Recent LSOA Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105499 entries, 0 to 105498
Data columns (total 29 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LSOA Code       105499 non-null  object
 1   LSOA Name       105499 non-null  object
 2   Borough         105499 non-null  object
 3   Major Category  105499 non-null  object
 4   Minor Category  105499 non-null  object
 5   202112          105499 non-null  int64
 6   202201          105499 non-null  int64
 7   202202          105499 non-null  int64
 8   202203          105499 non-null  int64
 9   202204          105499 non-null  int64
 10  202205          105499 non-null  int64
 11  202206          105499 non-null  int64
 12  202207          105499 non-null  int64
 13  202208          105499 non-null  int64
 14  202209          105499 non-null  int64
 15  202210          105499 non-null  int64
 16  202211          105499 non-null  int64
 17  202212          105499 non-null  int64
 18  202301          105499 non-null  int64
 19  202302          105499 non-null  int64
 20  202303          105499 non-null  int64
 21  202304          105499 non-null  int64
 22  202305          105499 non-null  int64
 23  202306          105499 non-null  int64
 24  202307          105499 non-null  int64
 25  202308          105499 non-null  int64
 26  202309          105499 non-null  int64
 27  202310          105499 non-null  int64
 28  202311          105499 non-null  int64
dtypes: int64(24), object(5)
memory usage: 23.3+ MB
None

Historical Ward Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29582 entries, 0 to 29581
Columns: 147 entries, WardName to 202201
dtypes: int64(142), object(5)
memory usage: 33.2+ MB
None

Recent Ward Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23428 entries, 0 to 23427
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MajorText           23428 non-null  object
 1   MinorText           23428 non-null  object
 2   WardName            23428 non-null  object
 3   WardCode            23428 non-null  object
 4   LookUp_BoroughName  23428 non-null  object
 5   202202              23428 non-null  int64
 6   202203              23428 non-null  int64
 7   202204              23428 non-null  int64
 8   202205              23428 non-null  int64
 9   202206              23428 non-null  int64
 10  202207              23428 non-null  int64
 11  202208              23428 non-null  int64
 12  202209              23428 non-null  int64
 13  202210              23428 non-null  int64
 14  202211              23428 non-null  int64
 15  202212              23428 non-null  int64
 16  202301              23428 non-null  int64
 17  202302              23428 non-null  int64
 18  202303              23428 non-null  int64
 19  202304              23428 non-null  int64
 20  202305              23428 non-null  int64
 21  202306              23428 non-null  int64
 22  202307              23428 non-null  int64
 23  202308              23428 non-null  int64
 24  202309              23428 non-null  int64
 25  202310              23428 non-null  int64
 26  202311              23428 non-null  int64
 27  202312              23428 non-null  int64
 28  202401              23428 non-null  int64
dtypes: int64(24), object(5)
memory usage: 5.2+ MB
None

Reported Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  66 non-null     int64
 1   crimes.total          66 non-null     int64
 2   crimes.penal.code     66 non-null     int64
 3   crimes.person         66 non-null     int64
 4   murder                66 non-null     int64
 5   assault               66 non-null     int64
 6   sexual.offenses       66 non-null     int64
 7   rape                  66 non-null     int64
 8   stealing.general      66 non-null     int64
 9   burglary              66 non-null     int64
 10  house.theft           51 non-null     float64
 11  vehicle.theft         59 non-null     float64
 12  out.of.vehicle.theft  51 non-null     float64
 13  shop.theft            51 non-null     float64
 14  robbery               66 non-null     int64
 15  fraud                 66 non-null     int64
 16  criminal.damage       66 non-null     int64
 17  other.penal.crimes    66 non-null     int64
 18  narcotics             62 non-null     float64
 19  drunk.driving         66 non-null     int64
 20  population            66 non-null     int64
dtypes: float64(5), int64(16)
memory usage: 11.0 KB
None

Homicides Crime Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3733 entries, 0 to 3732
Data columns (total 7 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   T11                                     3733 non-null   object
 1   Intentional homicides and other crimes  3732 non-null   object
 2   Unnamed: 2                              3733 non-null   object
 3   Unnamed: 3                              3733 non-null   object
 4   Unnamed: 4                              3733 non-null   object
 5   Unnamed: 5                              1 non-null      object
 6   Unnamed: 6                              3733 non-null   object
dtypes: object(7)
memory usage: 204.3+ KB
None

Historical Crime Data Description:
            201004       201005       201006       201007       201008  \
count   931.000000   931.000000   931.000000   931.000000   931.000000
mean     70.552095    74.764769    75.638024    77.058002    71.331901
std     101.020866   105.447054   104.581876   110.776647   102.714431
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       7.000000     8.000000     8.000000     8.000000     6.000000
50%      26.000000    29.000000    29.000000    30.000000    28.000000
75%     107.000000   108.500000   115.000000   111.500000   109.000000
max    1608.000000  1595.000000  1527.000000  1769.000000  1542.000000

            201009       201010       201011       201012       201101  ...  \
count   931.000000   931.000000   931.000000   931.000000   931.000000  ...
mean     72.262084    74.949517    73.205156    62.198711    70.424275  ...
std     102.856796   110.755017   109.577565    97.820278   104.746511  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       7.000000     7.000000     8.000000     6.000000     7.000000  ...
50%      28.000000    28.000000    26.000000    21.000000    24.000000  ...
75%     107.500000   109.500000   108.000000    92.000000   104.500000  ...
max    1595.000000  1849.000000  1769.000000  1776.000000  1731.000000  ...

            202107      202108      202109       202110       202111  \
count   931.000000  931.000000  931.000000   931.000000   931.000000
mean     76.297530   72.388829   75.586466    81.751880    79.832438
std     109.684683  101.211347  106.282641   120.060216   117.540567
min       0.000000    0.000000    0.000000     0.000000     0.000000
25%       9.000000    9.000000   10.000000    11.000000    11.000000
50%      35.000000   31.000000   35.000000    37.000000    38.000000
75%      98.500000   97.000000   99.000000   108.500000   107.000000
max    1095.000000  958.000000  996.000000  1448.000000  1382.000000

            202112       202201       202202       202203       202204
count   931.000000   931.000000   931.000000   931.000000   931.000000
mean     72.451128    73.699248    70.817401    79.204082    73.874329
std     112.517241   105.634549   106.304649   119.561049   112.086383
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       9.000000     9.000000     9.000000    10.000000     9.000000
50%      31.000000    34.000000    33.000000    36.000000    33.000000
75%      95.000000    97.000000    92.500000   105.000000    96.500000
max    1359.000000  1060.000000  1222.000000  1442.000000  1356.000000

[8 rows x 145 columns]

Recent Crime Data Description:
            202205       202206       202207       202208       202209  \
count   999.000000   999.000000   999.000000   999.000000   999.000000
mean     75.936937    73.612613    75.601602    73.746747    69.838839
std     119.243360   117.601229   129.475214   116.353940   110.236742
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       6.000000     5.000000     6.000000     6.000000     6.000000
50%      33.000000    31.000000    32.000000    31.000000    28.000000
75%      99.000000   100.000000    96.500000   101.000000    95.000000
max    1391.000000  1584.000000  2023.000000  1642.000000  1526.000000

            202210       202211       202212       202301       202302  ...  \
count   999.000000   999.000000   999.000000   999.000000   999.000000  ...
mean     76.922923    76.347347    69.726727    74.132132    69.956957  ...
std     137.215171   146.600238   149.673581   135.719454   128.450099  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       6.000000     7.000000     4.000000     6.000000     5.000000  ...
50%      31.000000    30.000000    26.000000    29.000000    28.000000  ...
75%     100.000000    98.000000    88.000000    98.000000    90.500000  ...
max    2224.000000  2524.000000  2665.000000  2189.000000  2012.000000  ...

            202307       202308       202309       202310       202311  \
count   999.000000   999.000000   999.000000   999.000000   999.000000
mean     80.584585    76.818819    77.752753    82.491491    79.748749
std     141.547511   127.500679   126.940623   153.526781   169.479233
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       8.000000     8.000000     9.000000     8.000000     8.000000
50%      32.000000    32.000000    32.000000    32.000000    30.000000
75%     103.000000   100.500000   104.000000   103.000000   102.000000
max    2234.000000  1881.000000  1784.000000  2065.000000  3310.000000

            202312       202401       202402       202403       202404
count   999.000000   999.000000   999.000000   999.000000   999.000000
mean     77.878879    75.579580    75.070070    76.592593    75.093093
std     168.123184   142.092435   152.391974   153.627465   141.053758
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       7.000000     8.000000     8.000000     7.000000     7.000000
50%      28.000000    28.000000    30.000000    30.000000    31.000000
75%      97.000000    97.000000    89.000000    94.500000    94.500000
max    3403.000000  2620.000000  2921.000000  3305.000000  2779.000000

[8 rows x 24 columns]

Historical LSOA Crime Data Description:
              201903         201904         201905         201906  \
count  153453.000000  153453.000000  153453.000000  153453.000000
mean        0.494901       0.467022       0.481985       0.478629
std         2.764873       2.714113       2.411734       2.359617
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max       464.000000     385.000000     348.000000     318.000000

              201907         201908         201909         201910  \
count  153453.000000  153453.000000  153453.000000  153453.000000
mean        0.506970       0.475103       0.471623       0.505549
std         2.274146       2.133176       2.167605       2.477733
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max       290.000000     275.000000     300.000000     326.000000

              201911         201912  ...         202102         202103  \
count  153453.000000  153453.000000  ...  153453.000000  153453.000000
mean        0.492548       0.470274  ...       0.326641       0.385669
std         2.469007       2.631156  ...       0.949015       1.070244
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.000000       0.000000  ...       0.000000       0.000000
50%         0.000000       0.000000  ...       0.000000       0.000000
75%         0.000000       0.000000  ...       0.000000       0.000000
max       363.000000     473.000000  ...      39.000000      39.000000

              202104         202105         202106         202107  \
count  153453.000000  153453.000000  153453.000000  153453.000000
mean        0.382488       0.417457       0.430796       0.439242
std         1.183269       1.444360       1.523398       1.719618
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max        99.000000     175.000000     173.000000     225.000000

              202108         202109         202110         202111
count  153453.000000  153453.000000  153453.000000  153453.000000
mean        0.413306       0.427851       0.462383       0.451532
std         1.596748       1.637717       2.164199       2.149301
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max       143.000000     181.000000     302.000000     364.000000

[8 rows x 140 columns]

Recent LSOA Crime Data Description:
              202112         202201         202202         202203  \
count  105499.000000  105499.000000  105499.000000  105499.000000
mean        0.598262       0.608385       0.583456       0.651144
std         2.653500       2.289100       2.504386       2.767831
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         1.000000       1.000000       1.000000       1.000000
max       420.000000     309.000000     348.000000     393.000000

              202204         202205         202206         202207  \
count  105499.000000  105499.000000  105499.000000  105499.000000
mean        0.610063       0.670935       0.651466       0.666954
std         2.622315       2.675468       2.679776       3.105667
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         1.000000       1.000000       1.000000       1.000000
max       369.000000     343.000000     320.000000     412.000000

              202208         202209  ...         202302         202303  \
count  105499.000000  105499.000000  ...  105499.000000  105499.000000
mean        0.652935       0.617134  ...       0.622499       0.677428
std         2.483209       2.332779  ...       3.547288       3.341881
min         0.000000       0.000000  ...       0.000000       0.000000
25%         0.000000       0.000000  ...       0.000000       0.000000
50%         0.000000       0.000000  ...       0.000000       0.000000
75%         1.000000       1.000000  ...       1.000000       1.000000
max       303.000000     311.000000  ...     492.000000     409.000000

              202304         202305         202306         202307  \
count  105499.000000  105499.000000  105499.000000  105499.000000
mean        0.645286       0.713372       0.731078       0.728102
std         3.087236       3.287566       3.429715       3.419860
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         1.000000       1.000000       1.000000       1.000000
max       411.000000     412.000000     437.000000     427.000000

              202308         202309         202310         202311
count  105499.000000  105499.000000  105499.000000  105499.000000
mean        0.695466       0.702708       0.687106       0.721950
std         2.898365       2.888241       3.600460       5.189294
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         1.000000       1.000000       1.000000       1.000000
max       309.000000     317.000000     513.000000     975.000000

[8 rows x 24 columns]

Historical Ward Crime Data Description:
             201004        201005        201006        201007        201008  \
count  29582.000000  29582.000000  29582.000000  29582.000000  29582.000000
mean       2.264688      2.337604      2.362044      2.403286      2.224495
std        7.495907      7.602230      7.294828      7.992307      7.536859
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        2.000000      2.000000      2.000000      2.000000      2.000000
max      654.000000    669.000000    630.000000    730.000000    623.000000

             201009        201010        201011        201012        201101  \
count  29582.000000  29582.000000  29582.000000  29582.000000  29582.000000
mean       2.254411      2.339801      2.289399      1.951254      2.202285
std        7.453008      8.430139      8.258463      7.748815      8.065550
min        0.000000      0.000000      0.000000      0.000000      0.000000

Trin 3: Håndtering af Manglende Værdier
jeg vil rense dataene ved at håndtere manglende værdier. Dette kan gøres ved at udfylde manglende værdier med forrige/efterfølgende værdier eller ved at fjerne rækker/kolonner med mange manglende værdier.

In [5]:
# Funktion til at tjekke manglende værdier i et datasæt
def check_missing_values(df, name):
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if missing.empty:
        print(f"{name} har ingen manglende værdier.")
    else:
        print(f"{name} har manglende værdier:\n{missing}")

# Kontrollér alle datasæt
check_missing_values(historical_crime_data, 'Historical Crime Data')
check_missing_values(recent_crime_data, 'Recent Crime Data')
check_missing_values(historical_lsoa_crime_data, 'Historical LSOA Crime Data')
check_missing_values(recent_lsoa_crime_data, 'Recent LSOA Crime Data')
check_missing_values(historical_ward_crime_data, 'Historical Ward Crime Data')
check_missing_values(recent_ward_crime_data, 'Recent Ward Crime Data')
check_missing_values(reported_crime_data, 'Reported Crime Data')
check_missing_values(homicides_crime_data, 'Homicides Crime Data')

Historical Crime Data har ingen manglende værdier.
Recent Crime Data har ingen manglende værdier.
Historical LSOA Crime Data har ingen manglende værdier.
Recent LSOA Crime Data har ingen manglende værdier.
Historical Ward Crime Data har ingen manglende værdier.
Recent Ward Crime Data har ingen manglende værdier.
Reported Crime Data har manglende værdier:
house.theft             15
vehicle.theft            7
out.of.vehicle.theft    15
shop.theft              15
dtype: int64
Homicides Crime Data har manglende værdier:
Intentional homicides and other crimes    1
dtype: int64

Data Cleaning Process
1. Håndtering af Manglende Værdier i Reported Crime Data
Jeg vil udfylde de manglende værdier med medianen for hver kolonne, der har manglende værdier.

In [7]:
# Udfyldning af manglende værdier i reported_crime_data ved brug af median
reported_crime_data['house.theft'] = reported_crime_data['house.theft'].fillna(reported_crime_data['house.theft'].median())
reported_crime_data['vehicle.theft'] = reported_crime_data['vehicle.theft'].fillna(reported_crime_data['vehicle.theft'].median())
reported_crime_data['out.of.vehicle.theft'] = reported_crime_data['out.of.vehicle.theft'].fillna(reported_crime_data['out.of.vehicle.theft'].median())
reported_crime_data['shop.theft'] = reported_crime_data['shop.theft'].fillna(reported_crime_data['shop.theft'].median())

2. Håndtering af Manglende Værdier i Homicides Crime Data
Jeg vil udfylde den manglende værdi med medianen for Intentional homicides and other crimes.

Trin 1: Indlæsning af Data og Forståelse af Strukturen
Indlæsning af Data og Forståelse af Strukturen: Jeg indlæser dataene og undersøger de første par rækker for at forstå dataens struktur og identificere relevante kolonner.

In [9]:
# Undersøg kolonnen for ikke-numeriske værdier
print(homicides_crime_data['Intentional homicides and other crimes'].unique())

[nan 'Total, all countries or areas' 'Africa' 'Americas'
 'Northern America' 'Caribbean' 'Central America' 'South America' 'Asia'
 'Central Asia' 'Eastern Asia' 'South-eastern Asia' 'Southern Asia'
 'Western Asia' 'Europe' 'Eastern Europe' 'Northern Europe'
 'Southern Europe' 'Western Europe' 'Oceania' 'Australia and New Zealand'
 'Afghanistan' 'Albania' 'Algeria' 'American Samoa' 'Andorra' 'Angola'
 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bolivia (Plurin. State of)' 'Bosnia and Herzegovina' 'Botswana' 'Brazil'
 'British Virgin Islands' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Cayman Islands'
 'Central African Republic' 'Channel Islands' 'Chile' 'China'
 'China, Hong Kong SAR' 'China, Macao SAR' 'Colombia' 'Cook Islands'
 'Costa Rica' 'Côte d’Ivoire' 'Croatia' 'Cuba' 'Curaçao' 'Cyprus'
 'Czechia' 'Denmark' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji' 'Finland' 'France'
 'French Guiana' 'French Polynesia' 'Georgia' 'Germany' 'Ghana'
 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Holy See'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia'
 'Iran (Islamic Republic of)' 'Iraq' 'Ireland' 'Isle of Man' 'Israel'
 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Latvia' 'Lebanon' 'Lesotho' 'Liberia'
 'Liechtenstein' 'Lithuania' 'Luxembourg' 'Madagascar' 'Malawi' 'Malaysia'
 'Maldives' 'Malta' 'Martinique' 'Mauritius' 'Mayotte' 'Mexico' 'Monaco'
 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar'
 'Namibia' 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niger' 'Nigeria' 'North Macedonia' 'Norway' 'Oman'
 'Other non-specified areas' 'Pakistan' 'Palau' 'Panama'
 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Puerto Rico' 'Qatar' 'Republic of Korea' 'Republic of Moldova' 'Réunion'
 'Romania' 'Russian Federation' 'Rwanda' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent & Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'South Africa' 'South Sudan' 'Spain' 'Sri Lanka'
 'State of Palestine' 'Sudan' 'Suriname' 'Sweden' 'Switzerland'
 'Syrian Arab Republic' 'Tajikistan' 'Thailand' 'Timor-Leste' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United Rep. of Tanzania'
 'United States of America' 'United States Virgin Islands' 'Uruguay'
 'Uzbekistan' 'Venezuela (Boliv. Rep. of)' 'Viet Nam' 'Yemen' 'Zambia'
 'Zimbabwe']

Trin 2: Konvertering til Numerisk
Konvertering til Numerisk: Vi konverterer kolonnen "Intentional homicides and other crimes" til numeriske værdier. Ikke-numeriske værdier tvinges til NaN for at sikre, at kun numeriske data behandles.

In [10]:
# Forsøg at konvertere kolonnen til numerisk og tving ikke-numeriske værdier til NaN
homicides_crime_data['Intentional homicides and other crimes'] = pd.to_numeric(homicides_crime_data['Intentional homicides and other crimes'], errors='coerce')

# Undersøg de første par rækker for at kontrollere resultatet
print(homicides_crime_data.head())

                   T11  Intentional homicides and other crimes Unnamed: 2  \
0  Region/Country/Area                                     NaN       Year
1                    1                                     NaN       2005
2                    1                                     NaN       2005
3                    1                                     NaN       2005
4                    1                                     NaN       2010

                                          Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0                                             Series      Value  Footnotes
1             Intentional homicide rates per 100,000     6.2935  Footnotes
2  Percentage of male and female intentional homi...    10.0798  Footnotes
3  Percentage of male and female intentional homi...     2.4473  Footnotes
4             Intentional homicide rates per 100,000     6.0228  Footnotes

                                          Unnamed: 6
0                                             Source
1  United Nations Office on Drugs and Crime (UNOD...
2  United Nations Office on Drugs and Crime (UNOD...
3  United Nations Office on Drugs and Crime (UNOD...
4  United Nations Office on Drugs and Crime (UNOD...

Trin 3: Filtrering af Relevante Rækker
Filtrering af Relevante Rækker: Vi fjerner rækker, hvor kolonnen "Intentional homicides and other crimes" indeholder NaN. Dette sikrer, at vi kun arbejder med relevante numeriske værdier.

In [12]:
# Filtrér rækker hvor "Intentional homicides and other crimes" ikke er NaN
homicides_crime_data = homicides_crime_data.dropna(subset=['Intentional homicides and other crimes'])

# Undersøg de første par rækker igen for at kontrollere resultatet
print(homicides_crime_data.head())

Empty DataFrame
Columns: [T11, Intentional homicides and other crimes, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6]
Index: []

3. Validering af Data Cleaning
Efter at have udfyldt de manglende værdier, validerer Jeg, at der ikke er flere manglende værdier.

Trin 4: Udfyldning af Manglende Værdier
Udfyldning af Manglende Værdier: Vi udfylder eventuelle manglende værdier med medianen. Medianen bruges, fordi den er robust over for outliers og giver en repræsentativ værdi for dataene.

In [13]:
# Udfyldning af manglende værdier med median
homicides_crime_data['Intentional homicides and other crimes'] = homicides_crime_data['Intentional homicides and other crimes'].fillna(homicides_crime_data['Intentional homicides and other crimes'].median())

# Validering af manglende værdier
print("Homicides Crime Data Missing Values efter rengøring:\n", homicides_crime_data.isnull().sum())

Homicides Crime Data Missing Values efter rengøring:
 T11                                       0
Intentional homicides and other crimes    0
Unnamed: 2                                0
Unnamed: 3                                0
Unnamed: 4                                0
Unnamed: 5                                0
Unnamed: 6                                0
dtype: int64

In [24]:
# Validering af manglende værdier
print("Reported Crime Data Missing Values efter rengøring:\n", reported_crime_data.isnull().sum())
print("Homicides Crime Data Missing Values efter rengøring:\n", homicides_crime_data.isnull().sum())

# Gemme rensede versioner af CSV-filerne
historical_crime_data.to_csv('Cleaned_MPS_Borough_Level_Crime_Historical.csv', index=False)
recent_crime_data.to_csv('Cleaned_MPS_Borough_Level_Crime_Recent.csv', index=False)
historical_lsoa_crime_data.to_csv('Cleaned_MPS_LSOA_Level_Crime_Historical.csv', index=False)
recent_lsoa_crime_data.to_csv('Cleaned_MPS_LSOA_Level_Crime_Recent.csv', index=False)
historical_ward_crime_data.to_csv('Cleaned_MPS_Ward_Level_Crime_Historical.csv', index=False)
recent_ward_crime_data.to_csv('Cleaned_MPS_Ward_Level_Crime_Recent.csv', index=False)
homicides_crime_data.to_csv('Cleaned_Intentional_Homicides_and_Other_Crimes.csv', index=False)
reported_crime_data.to_csv('Cleaned_Reported_Crime_Data.csv', index=False)


print("Alle rensede filer er gemt.")

Reported Crime Data Missing Values efter rengøring:
 Year                    0
crimes.total            0
crimes.penal.code       0
crimes.person           0
murder                  0
assault                 0
sexual.offenses         0
rape                    0
stealing.general        0
burglary                0
house.theft             0
vehicle.theft           0
out.of.vehicle.theft    0
shop.theft              0
robbery                 0
fraud                   0
criminal.damage         0
other.penal.crimes      0
narcotics               0
drunk.driving           0
population              0
dtype: int64
Homicides Crime Data Missing Values efter rengøring:
 T11                                       0
Intentional homicides and other crimes    0
Unnamed: 2                                0
Unnamed: 3                                0
Unnamed: 4                                0
Unnamed: 5                                0
Unnamed: 6                                0
dtype: int64
Alle rensede filer er gemt.